# Writes cpp/swegca_vrs/unicode_casefold.hpp from Unicode
# CaseFolding.txt: every mapping of status C or F, the full case folding
# that Python's str.casefold applies (the user's `_cue`). Usage:
#   awk -f tools/generate_casefold_table.awk third_party/unicode/CaseFolding-16.0.0.txt \
#       > cpp/swegca_vrs/unicode_casefold.hpp
BEGIN { FS = "; "; count = 0; version = "" }
NR == 1 {
    if (match($0, /CaseFolding-[0-9.]+[0-9]/) == 0) { print "no version line" > "/dev/stderr"; exit 1 }
    version = substr($0, RSTART + 12, RLENGTH - 12)
}
/^[0-9A-F]+; [CF]; / {
    n = split($3, to, " ")
    if (n < 1 || n > 3) { print "bad mapping: " $0 > "/dev/stderr"; exit 1 }
    line = sprintf("    {0x%s, %d, {0x%s, 0x%s, 0x%s}},", $1, n, to[1], (n > 1 ? to[2] : "0"), (n > 2 ? to[3] : "0"))
    rows[count++] = line
    if (count > 1 && strtonum_hex($1) <= prev) { print "not increasing: " $1 > "/dev/stderr"; exit 1 }
    prev = strtonum_hex($1)
}
END {
    if (version == "" || count == 0) exit 1
    print "#pragma once"
    print ""
    print "// Generated by tools/generate_casefold_table.awk from Unicode"
    print "// CaseFolding.txt " version " (status C and F). Do not edit."
    print ""
    print "#include <array>"
    print "#include <cstddef>"
    print "#include <cstdint>"
    print "#include <string_view>"
    print ""
    print "namespace swegca::vrs::detail {"
    print ""
    print "inline constexpr std::string_view case_folding_unicode_version = \"" version "\";"
    print ""
    print "// One full case folding: a code point and the 1-3 code points it folds to."
    print "// SWEGCA: src/tinylm_slicer/mosaic_memory_activation.py@3bddcb7:34-35"
    print "struct CaseFolding final {"
    print "    char32_t from;"
    print "    std::uint8_t count;"
    print "    std::array<char32_t, 3> to;"
    print "};"
    print ""
    print "// Sorted by `from`, strictly increasing."
    print "// SWEGCA: src/tinylm_slicer/mosaic_memory_activation.py@3bddcb7:34-35"
    print "inline constexpr std::array<CaseFolding, " count "> case_foldings{{"
    for (i = 0; i < count; ++i) print rows[i]
    print "}};"
    print ""
    print "}  // namespace swegca::vrs::detail"
}
function strtonum_hex(h,    i, c, v) {
    v = 0
    for (i = 1; i <= length(h); ++i) { c = index("0123456789ABCDEF", substr(h, i, 1)) - 1; v = v * 16 + c }
    return v
}
