#!/usr/bin/env python3
"""Generate the self-contained Unicode 16.0.0 tables used by the C++ NFKC port."""

from __future__ import annotations

import argparse
import unicodedata
from pathlib import Path


UNICODE_VERSION = "16.0.0"
HANGUL_FIRST = 0xAC00
HANGUL_LAST = 0xD7A3


def _format(values: list[int], width: int = 12) -> str:
    rows = []
    for index in range(0, len(values), width):
        rows.append("    " + ", ".join(f"0x{value:x}u" for value in values[index:index + width]))
    return ",\n".join(rows)


def generate(output: Path) -> None:
    if unicodedata.unidata_version != UNICODE_VERSION:
        raise SystemExit(
            f"generator requires Unicode {UNICODE_VERSION}, got {unicodedata.unidata_version}"
        )

    decomposition_entries: list[tuple[int, int, int]] = []
    decomposition_values: list[int] = []
    combining_entries: list[tuple[int, int]] = []
    composition_entries: list[tuple[int, int, int]] = []
    casefold_entries: list[tuple[int, int, int]] = []
    casefold_values: list[int] = []
    whitespace: list[int] = []

    for point in range(0x110000):
        if HANGUL_FIRST <= point <= HANGUL_LAST:
            continue
        normalized = unicodedata.normalize("NFKD", chr(point))
        values = [ord(value) for value in normalized]
        if values != [point]:
            decomposition_entries.append(
                (point, len(decomposition_values), len(values))
            )
            decomposition_values.extend(values)
        combining = unicodedata.combining(chr(point))
        if combining:
            combining_entries.append((point, combining))
        folded = [ord(value) for value in chr(point).casefold()]
        if folded != [point]:
            casefold_entries.append((point, len(casefold_values), len(folded)))
            casefold_values.extend(folded)
        if chr(point).isspace():
            whitespace.append(point)

        raw = unicodedata.decomposition(chr(point))
        if not raw or raw.startswith("<"):
            continue
        parts = [int(value, 16) for value in raw.split()]
        if len(parts) != 2:
            continue
        if unicodedata.normalize("NFC", "".join(map(chr, parts))) == chr(point):
            composition_entries.append((parts[0], parts[1], point))

    composition_entries.sort(key=lambda value: (value[0], value[1]))
    text = f'''// Generated by tools/generate_unicode_nfkc_tables.py. Do not edit.
// Python unicodedata version: {UNICODE_VERSION}
#pragma once

#include <array>
#include <cstdint>

namespace swegca::world::unicode_data {{

struct DecompositionEntry final {{
    char32_t point;
    std::uint32_t offset;
    std::uint16_t size;
}};
struct CombiningEntry final {{ char32_t point; std::uint8_t value; }};
struct CompositionEntry final {{ char32_t first; char32_t second; char32_t value; }};
struct CasefoldEntry final {{
    char32_t point;
    std::uint32_t offset;
    std::uint8_t size;
}};

inline constexpr std::array<char32_t, {len(decomposition_values)}> decomposition_values{{{{
{_format(decomposition_values)}
}}}};
inline constexpr std::array<DecompositionEntry, {len(decomposition_entries)}> decompositions{{{{
''' + "\n".join(
        f"    {{0x{point:x}u, {offset}u, {size}u}},"
        for point, offset, size in decomposition_entries
    ) + f'''
}}}};
inline constexpr std::array<CombiningEntry, {len(combining_entries)}> combining_classes{{{{
''' + "\n".join(
        f"    {{0x{point:x}u, {value}u}}," for point, value in combining_entries
    ) + f'''
}}}};
inline constexpr std::array<CompositionEntry, {len(composition_entries)}> compositions{{{{
''' + "\n".join(
        f"    {{0x{first:x}u, 0x{second:x}u, 0x{value:x}u}},"
        for first, second, value in composition_entries
    ) + f'''
}}}};
inline constexpr std::array<char32_t, {len(casefold_values)}> casefold_values{{{{
{_format(casefold_values)}
}}}};
inline constexpr std::array<CasefoldEntry, {len(casefold_entries)}> casefolds{{{{
''' + "\n".join(
        f"    {{0x{point:x}u, {offset}u, {size}u}},"
        for point, offset, size in casefold_entries
    ) + f'''
}}}};
inline constexpr std::array<char32_t, {len(whitespace)}> whitespace{{{{
{_format(whitespace)}
}}}};

}}  // namespace swegca::world::unicode_data
'''
    output.write_text(text, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(args.output)


if __name__ == "__main__":
    main()
