#!/usr/bin/env python3
r"""Generate C++ Unicode primitive tables for the author's keys() semantics.

The generated table is source data, not a Python runtime dependency. It
captures the pinned product Python 3.12 / Unicode 15 re ``\w`` and
str.casefold behavior used by
src/swegca_vrs2/store.py@7536139:72-79. Regenerate only when the pinned
author Unicode behavior is deliberately updated.
"""

from __future__ import annotations

from pathlib import Path
import re
import sys
import unicodedata


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "cpp" / "unicode_tables.hpp"
WORD = re.compile(r"\w", re.UNICODE)


def main() -> None:
    if sys.version_info[:2] != (3, 12) or unicodedata.unidata_version != "15.0.0":
        raise RuntimeError("unicode tables require product Python 3.12 / Unicode 15.0.0")
    ranges: list[tuple[int, int]] = []
    mappings: list[tuple[int, int, int]] = []
    replacements: list[int] = []
    range_start: int | None = None
    for point in range(0x110000):
        character = chr(point)
        word = WORD.fullmatch(character) is not None
        if word and range_start is None:
            range_start = point
        elif not word and range_start is not None:
            ranges.append((range_start, point - 1))
            range_start = None
        if 0xD800 <= point <= 0xDFFF:
            continue
        folded = tuple(ord(item) for item in character.casefold())
        if folded != (point,):
            mappings.append((point, len(replacements), len(folded)))
            replacements.extend(folded)
    if range_start is not None:
        ranges.append((range_start, 0x10FFFF))
    if max(length for _, _, length in mappings) > 255:
        raise RuntimeError("casefold expansion exceeds uint8")

    lines = [
        "// Generated by tools/generate_unicode_tables.py with Python " + sys.version.split()[0],
        "// Unicode " + unicodedata.unidata_version,
        "// SWEGCA: src/swegca_vrs2/store.py@7536139:72-79",
        "#pragma once",
        "#include <cstdint>",
        "namespace swegca::vrs::unicode_table {",
        "struct WordRange { std::uint32_t first; std::uint32_t last; };",
        "struct FoldMapping { std::uint32_t point; std::uint32_t offset; std::uint8_t count; };",
        "inline constexpr WordRange word_ranges[] = {",
    ]
    lines.extend(f"    {{0x{first:x}u, 0x{last:x}u}}," for first, last in ranges)
    lines.extend(["};", "inline constexpr FoldMapping fold_mappings[] = {"])
    lines.extend(
        f"    {{0x{point:x}u, {offset}u, {length}u}},"
        for point, offset, length in mappings
    )
    lines.extend(["};", "inline constexpr std::uint32_t fold_codepoints[] = {"])
    for at in range(0, len(replacements), 12):
        lines.append("    " + ", ".join(f"0x{point:x}u" for point in replacements[at:at + 12]) + ",")
    lines.extend(["};", "}  // namespace swegca::vrs::unicode_table", ""])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated {OUTPUT}: {len(ranges)} word ranges, {len(mappings)} casefold mappings")


if __name__ == "__main__":
    main()
