#include "world/media_atoms.hpp"

#include "world/semantic_vrs_ingress.hpp"

#include <algorithm>
#include <array>
#include <set>
#include <stdexcept>

namespace swegca::world {
namespace {

const JsonValue* find(const JsonValue::Object& object,const std::string_view key){const auto at=object.find(key);return at==object.end()?nullptr:&at->second;}
const JsonValue::Object& object(const JsonValue& value){if(!value.is_object())throw std::invalid_argument("media observation mapping required");return value.as_object();}
std::string text(const JsonValue::Object& value,const std::string_view key){const auto* item=find(value,key);if(!item)return {};const auto* result=std::get_if<std::string>(&item->storage());if(!result)throw std::invalid_argument("media text field changed");return *result;}
std::int64_t integer(const JsonValue::Object& value,const std::string_view key){const auto* item=find(value,key);const auto* result=item?std::get_if<std::int64_t>(&item->storage()):nullptr;if(!result)throw std::invalid_argument("media integer field changed");return *result;}
bool boolean(const JsonValue::Object& value,const std::string_view key){const auto* item=find(value,key);const auto* result=item?std::get_if<bool>(&item->storage()):nullptr;if(!result)throw std::invalid_argument("media boolean field changed");return *result;}
std::vector<std::int64_t> integers(const JsonValue& value){if(!value.is_array())throw std::invalid_argument("media coordinate array changed");std::vector<std::int64_t> out;for(const auto& item:value.as_array()){const auto* v=std::get_if<std::int64_t>(&item.storage());if(!v)throw std::invalid_argument("media coordinate array changed");out.push_back(*v);}return out;}
JsonValue path_json(const std::vector<ObservationPathElement>& path){JsonValue::Array out;for(const auto& p:path){if(const auto* s=std::get_if<std::string>(&p))out.emplace_back(*s);else out.emplace_back(static_cast<std::int64_t>(std::get<std::size_t>(p)));}return out;}
JsonValue spatial_json(const std::optional<SpatialExtent>& value){if(!value)return nullptr;return JsonValue::Object{{"coordinate_frame",value->coordinate_frame},{"native_wh",JsonValue::Array{value->native_wh.first,value->native_wh.second}},{"original_xywh",JsonValue::Array{value->original_xywh[0],value->original_xywh[1],value->original_xywh[2],value->original_xywh[3]}}};}
JsonValue temporal_json(const std::optional<TemporalExtent>& value){if(!value)return nullptr;return JsonValue::Object{{"clock",value->clock},{"hardware_latency_ns",value->hardware_latency_ns?JsonValue(*value->hardware_latency_ns):JsonValue(nullptr)},{"precision",value->precision},{"start_ns",value->start_ns},{"stop_ns",value->stop_ns}};}
JsonValue samples_json(const std::optional<SampleExtent>& value){if(!value)return nullptr;return JsonValue::Object{{"sample_rate",value->sample_rate},{"start_frame",value->start_frame},{"stop_frame",value->stop_frame}};}
std::string address(const EpisodeAtoms& binding,const std::size_t index,const std::string& kind,const std::vector<ObservationPathElement>& path,const std::optional<SpatialExtent>& spatial,const std::optional<TemporalExtent>& temporal,const std::optional<SampleExtent>& samples){
    return experience_atom_identifier(JsonValue::Array{"media-selector-v1",binding.episode->episode_id,binding.episode->revision,static_cast<std::int64_t>(index),std::string(binding.steps[index].source_hash()),kind,path_json(path),spatial_json(spatial),temporal_json(temporal),samples_json(samples)});
}
JsonValue observation_root(const MemoryStep& step){return JsonValue(step.observation);}
}

SpatialExtent::SpatialExtent(std::pair<std::int64_t,std::int64_t> native,std::array<std::int64_t,4> region,std::string frame):native_wh(native),original_xywh(region),coordinate_frame(std::move(frame)){
    if(coordinate_frame!="native_source_pixels"&&coordinate_frame!="oriented_source_pixels")throw std::invalid_argument("explicit spatial coordinate frame required");
    const auto[w,h]=native_wh;const auto[x,y,rw,rh]=original_xywh;if(std::min({w,h,rw,rh})<=0||std::min(x,y)<0||x+rw>w||y+rh>h)throw std::invalid_argument("region outside native source");}
TemporalExtent::TemporalExtent(std::string clock_value,std::int64_t start,std::int64_t stop,std::string precision_value,std::optional<std::int64_t> latency):clock(std::move(clock_value)),start_ns(start),stop_ns(stop),precision(std::move(precision_value)),hardware_latency_ns(latency){if(clock.empty()||stop_ns<start_ns)throw std::invalid_argument("invalid explicit clock interval");if(precision!="recorded_point"&&precision!="estimated_capture_interval"&&precision!="sample_enclosing_ns")throw std::invalid_argument("timing precision must be explicit");if(hardware_latency_ns&&*hardware_latency_ns<0)throw std::invalid_argument("invalid latency uncertainty");}
SampleExtent::SampleExtent(std::int64_t start,std::int64_t stop,std::int64_t rate):start_frame(start),stop_frame(stop),sample_rate(rate){if(start_frame<0||start_frame>=stop_frame||sample_rate<=0)throw std::invalid_argument("invalid source sample span");}
std::pair<std::int64_t,std::int64_t> SampleExtent::enclosing_ns()const{return {start_frame*1'000'000'000/sample_rate,(stop_frame*1'000'000'000+sample_rate-1)/sample_rate};}
const MemoryStep& PreparedMediaSelector::replay_step()const{return episode->steps.at(selector.step_index);}
const JsonValue& observation_at(const JsonValue& root,const std::vector<ObservationPathElement>& path){const JsonValue* value=&root;for(const auto& part:path){if(const auto* key=std::get_if<std::string>(&part))value=&value->at(*key);else{if(!value->is_array())throw std::out_of_range("media observation path");value=&value->as_array().at(std::get<std::size_t>(part));}}return *value;}
EpisodeMediaSelectors::EpisodeMediaSelectors(const EpisodeAtoms* binding_value,std::vector<MediaSelector> values):binding(binding_value),selectors(std::move(values)){if(!binding)throw std::invalid_argument("immutable media selector generation required");std::set<std::string> ids;for(const auto& s:selectors)if(!ids.insert(s.atom_id).second)throw std::invalid_argument("duplicate media selector address");}

EpisodeMediaSelectors EpisodeMediaSelectors::build(const EpisodeAtoms& binding){binding.verify_cold();std::vector<MediaSelector> result;
    const auto add=[&](std::size_t index,std::string kind,std::vector<ObservationPathElement> path,std::optional<SpatialExtent> spatial={},std::optional<TemporalExtent> temporal={},std::optional<SampleExtent> samples={}){const auto root=observation_root(binding.episode->steps[index]);observation_at(root,path);result.push_back({address(binding,index,kind,path,spatial,temporal,samples),index,std::move(kind),std::move(path),std::move(spatial),std::move(temporal),std::move(samples)});};
    for(std::size_t index=0;index<binding.episode->steps.size();++index){const auto& obs=binding.episode->steps[index].observation;const auto* cv=find(obs,"content");JsonValue empty(JsonValue::Object{});const auto& content=object(cv?*cv:empty);const auto kind=text(obs,"media_kind");add(index,"retained_observation",{});
        if(kind=="image_tag_observation"||kind=="image_caption_observation"){const bool oriented=kind=="image_caption_observation";const auto dims=integers(content.at(oriented?"oriented_dimensions":"native_dimensions"));if(dims.size()!=2)throw std::invalid_argument("explicit integer coordinates required");std::pair<std::int64_t,std::int64_t> native{dims[0],dims[1]};const std::string frame=oriented?"oriented_source_pixels":"native_source_pixels";SpatialExtent whole(native,{0,0,native.first,native.second},frame);std::optional<TemporalExtent> time;
            if(const auto* capture_value=find(content,"capture_provenance")){const auto& capture=object(*capture_value);const auto stamp=integer(capture,"observed_at_monotonic_ns");const auto sd=integers(capture.at("source_dimensions_wh"));if(text(capture,"clock_domain")!="host-monotonic-ns"||stamp!=integer(content,"video_timestamp_ns")||text(capture,"source_sha256")!=text(content,"source_sha256")||sd!=dims)throw std::invalid_argument("screen timestamp binding changed");time=TemporalExtent(text(capture,"clock_domain"),stamp,stamp,"recorded_point");}
            add(index,time?"screen_frame":"image",{std::string("content")},whole,time);if(const auto* views=find(content,"views")){for(std::size_t j=0;j<views->as_array().size();++j){const auto region=integers(views->as_array()[j].at("source_region_original_xywh"));add(index,"visual_feature_region",{std::string("content"),std::string("views"),j},SpatialExtent(native,{region.at(0),region.at(1),region.at(2),region.at(3)},frame),time);}}
            if(const auto* tags=find(content,"tags"))for(std::size_t j=0;j<tags->as_array().size();++j)add(index,"tag_proposal",{std::string("content"),std::string("tags"),j},{},time);
            if(const auto* proposal=find(content,"proposal"))for(const auto&[key,unused]:proposal->as_object()){static_cast<void>(unused);add(index,"caption_proposal",{std::string("content"),std::string("proposal"),key},{},time);}}
        if(kind=="audio_waveform"){SampleExtent samples(0,integer(content,"frames"),integer(content,"sample_rate"));const auto[start,stop]=samples.enclosing_ns();if(integer(content,"duration_ns")!=samples.stop_frame*1'000'000'000/samples.sample_rate)throw std::invalid_argument("audio duration/sample binding changed");add(index,"audio_feature_record",{std::string("content")},{},TemporalExtent("source-relative-sample-clock",start,stop,"sample_enclosing_ns"),samples);}
        if(const auto* batch_value=find(content,"concurrent_system_audio")){const auto& batch=object(*batch_value);const auto& segments=batch.at("segments").as_array();if(integer(batch,"segment_count")!=static_cast<std::int64_t>(segments.size()))throw std::invalid_argument("acoustic segment count changed");for(std::size_t j=0;j<segments.size();++j){const auto& segment=object(segments[j]);if(text(segment,"schema_version")!="rozephine-system-audio-feature-v1"||text(segment,"clock_domain")!="host-monotonic-ns"||boolean(segment,"raw_pcm_retained")||boolean(segment,"waveform_reconstructable"))throw std::invalid_argument("system audio representation changed");SampleExtent samples(0,integer(segment,"frames"),integer(segment,"sample_rate"));TemporalExtent time(text(segment,"clock_domain"),integer(segment,"estimated_start_monotonic_ns"),integer(segment,"received_end_monotonic_ns"),"estimated_capture_interval",integer(segment,"hardware_latency_ns"));if(time.stop_ns-time.start_ns!=integer(segment,"duration_ns")||integer(segment,"duration_ns")!=samples.stop_frame*1'000'000'000/samples.sample_rate)throw std::invalid_argument("system audio duration/sample binding changed");add(index,"system_audio_feature_segment",{std::string("content"),std::string("concurrent_system_audio"),std::string("segments"),j},{},time,samples);}}
    }return EpisodeMediaSelectors(&binding,std::move(result));}

PreparedMediaSelector EpisodeMediaSelectors::prepare(const std::size_t index)const{if(index>=selectors.size())throw std::out_of_range("media selector outside bound generation");const auto& selector=selectors[index];if(selector.atom_id!=address(*binding,selector.step_index,selector.kind,selector.observation_path,selector.spatial,selector.temporal,selector.samples))throw std::invalid_argument("media selector source binding changed");const auto root=observation_root(binding->episode->steps[selector.step_index]);const auto& value=observation_at(root,selector.observation_path);const auto wire=semantic_canonical_json(value);return {selector,binding->episode,std::string(binding->steps[selector.step_index].source_hash()),{reinterpret_cast<const std::byte*>(wire.data()),reinterpret_cast<const std::byte*>(wire.data()+wire.size())}};}
} // namespace swegca::world
