#include "world/mosaic_omni_world_pipeline.hpp"

#include <algorithm>
#include <cmath>
#include <limits>
#include <ranges>
#include <stdexcept>
#include <utility>

namespace swegca::world {
namespace {

void linear_shape(const WorldPipelineLinear& w,std::size_t in,std::size_t out,bool bias=true){if(w.weight.size()!=in*out||(bias?w.bias.size()!=out:!w.bias.empty()))throw std::invalid_argument("world pipeline linear weight shape mismatch");}
Tensor linear(const Tensor& x,const WorldPipelineLinear& w,std::size_t out,bool bias=true){const auto s=x.shape();if(s.empty())throw std::invalid_argument("linear input rank mismatch");const auto in=static_cast<std::size_t>(s.back()),rows=x.values().size()/in;linear_shape(w,in,out,bias);std::vector<double> v(rows*out);for(std::size_t r=0;r<rows;++r)for(std::size_t o=0;o<out;++o){double z=w.bias.empty()?0:w.bias[o];for(std::size_t i=0;i<in;++i)z+=x.values()[r*in+i]*w.weight[o*in+i];v[r*out+o]=z;}std::vector<std::uint64_t> shape(s.begin(),s.end());shape.back()=out;return Tensor(x.dtype(),std::move(shape),std::move(v),std::string(x.device()));}
Tensor add(const Tensor&a,const Tensor&b){if(!std::ranges::equal(a.shape(),b.shape()))throw std::invalid_argument("world pipeline tensor shape mismatch");std::vector<double>v(a.values().size());for(std::size_t i=0;i<v.size();++i)v[i]=a.values()[i]+b.values()[i];return Tensor(a.dtype(),{a.shape().begin(),a.shape().end()},std::move(v),std::string(a.device()));}
Tensor concat_tokens(const std::vector<Tensor>& rows){if(rows.empty())throw std::invalid_argument("source tokens must be nonempty");const auto first=rows.front().shape();if(first.size()!=3)throw std::invalid_argument("source tokens must be rank three");std::size_t tokens=0;for(const auto&x:rows){const auto s=x.shape();if(s.size()!=3||s[0]!=first[0]||s[2]!=first[2])throw std::invalid_argument("source token shape mismatch");tokens+=s[1];}std::vector<double>v;v.reserve(first[0]*tokens*first[2]);for(std::size_t b=0;b<first[0];++b)for(const auto&x:rows){const auto s=x.shape();const auto begin=x.values().begin()+static_cast<std::ptrdiff_t>(b*s[1]*s[2]);v.insert(v.end(),begin,begin+static_cast<std::ptrdiff_t>(s[1]*s[2]));}return Tensor(rows.front().dtype(),{first[0],tokens,first[2]},std::move(v),std::string(rows.front().device()));}
BooleanMask concat_masks(const std::vector<BooleanMask>& rows){if(rows.empty())throw std::invalid_argument("source masks must be nonempty");const auto first=rows.front().shape();std::size_t tokens=0;for(const auto&m:rows){const auto s=m.shape();if(s.size()!=2||s[0]!=first[0])throw std::invalid_argument("source mask shape mismatch");tokens+=s[1];}std::vector<std::uint8_t>v;v.reserve(first[0]*tokens);for(std::size_t b=0;b<first[0];++b)for(const auto&m:rows){const auto s=m.shape();const auto begin=m.values().begin()+static_cast<std::ptrdiff_t>(b*s[1]);v.insert(v.end(),begin,begin+static_cast<std::ptrdiff_t>(s[1]));}return BooleanMask({first[0],tokens},std::move(v));}
void add_row_slots(std::vector<double>&world,std::size_t batch,std::size_t slots,std::size_t dim,std::size_t destination,const Tensor&source,std::size_t source_slot=0,bool replace=false){const auto s=source.shape();if(s.size()!=3||s[0]!=batch||s[2]!=dim||source_slot>=s[1]||destination>=slots)throw std::invalid_argument("slot injection shape mismatch");for(std::size_t b=0;b<batch;++b)for(std::size_t d=0;d<dim;++d){auto&target=world[(b*slots+destination)*dim+d];const auto value=source.values()[(b*s[1]+source_slot)*dim+d];target=replace?value:target+value;}}
Tensor adaptive_two(const Tensor&x){const auto s=x.shape();if(s.size()!=3||!s[1])throw std::invalid_argument("audio features must be [B,T,D]");const auto b=static_cast<std::size_t>(s[0]),t=static_cast<std::size_t>(s[1]),d=static_cast<std::size_t>(s[2]);std::vector<double>v(b*2*d);for(std::size_t row=0;row<b;++row)for(std::size_t out=0;out<2;++out){const auto start=static_cast<std::size_t>(std::floor(static_cast<double>(out*t)/2)),end=static_cast<std::size_t>(std::ceil(static_cast<double>((out+1)*t)/2));for(std::size_t i=start;i<end;++i)for(std::size_t j=0;j<d;++j)v[(row*2+out)*d+j]+=x.values()[(row*t+i)*d+j]/static_cast<double>(end-start);}return Tensor(x.dtype(),{b,2,d},std::move(v),std::string(x.device()));}
Tensor norm(const Tensor&x,std::span<const double>w,std::span<const double>bias){const auto s=x.shape();const auto d=static_cast<std::size_t>(s.back()),rows=x.values().size()/d;if(w.size()!=d||bias.size()!=d)throw std::invalid_argument("world norm shape mismatch");std::vector<double>v(x.values().size());for(std::size_t r=0;r<rows;++r){double m=0;for(std::size_t j=0;j<d;++j)m+=x.values()[r*d+j];m/=d;double q=0;for(std::size_t j=0;j<d;++j)q+=(x.values()[r*d+j]-m)*(x.values()[r*d+j]-m);const auto inv=1/std::sqrt(q/d+1e-5);for(std::size_t j=0;j<d;++j)v[r*d+j]=(x.values()[r*d+j]-m)*inv*w[j]+bias[j];}return Tensor(x.dtype(),{s.begin(),s.end()},std::move(v),std::string(x.device()));}
Tensor world_cell(const Tensor&input,const BooleanMask&mask,const MosaicOmniWorldPipelineConfig&c,const WorldPipelineCellWeights&w){const auto s=input.shape();const auto b=static_cast<std::size_t>(s[0]),n=static_cast<std::size_t>(s[1]),d=static_cast<std::size_t>(s[2]),h=c.attention_heads,hd=d/h;WorldPipelineLinear in{w.attention_in_weight,w.attention_in_bias},out{w.attention_out_weight,w.attention_out_bias};auto normalized=norm(input,w.norm1_weight,w.norm1_bias),qkv=linear(normalized,in,d*3);std::vector<double>joined(b*n*d),scores(n);for(std::size_t batch=0;batch<b;++batch)for(std::size_t head=0;head<h;++head)for(std::size_t q=0;q<n;++q){double maximum=-std::numeric_limits<double>::infinity();for(std::size_t k=0;k<n;++k){if(!mask.at(batch,k)){scores[k]=-std::numeric_limits<double>::infinity();continue;}double z=0;for(std::size_t j=0;j<hd;++j)z+=qkv.values()[(batch*n+q)*3*d+head*hd+j]*qkv.values()[(batch*n+k)*3*d+d+head*hd+j];scores[k]=z/std::sqrt(static_cast<double>(hd));maximum=std::max(maximum,scores[k]);}double sum=0;for(std::size_t k=0;k<n;++k)if(mask.at(batch,k)){scores[k]=std::exp(scores[k]-maximum);sum+=scores[k];}for(std::size_t j=0;j<hd;++j)for(std::size_t k=0;k<n;++k)if(mask.at(batch,k))joined[(batch*n+q)*d+head*hd+j]+=scores[k]/sum*qkv.values()[(batch*n+k)*3*d+2*d+head*hd+j];}auto state=add(input,linear(Tensor(input.dtype(),{b,n,d},std::move(joined),std::string(input.device())),out,d));auto hidden=linear(norm(state,w.norm2_weight,w.norm2_bias),w.feedforward_in,c.world_ffn_dim);std::vector<double>hv(hidden.values().begin(),hidden.values().end());for(auto&v:hv)v*=0.5*(1+std::erf(v/std::sqrt(2.0)));hidden=Tensor(hidden.dtype(),{hidden.shape().begin(),hidden.shape().end()},std::move(hv),std::string(hidden.device()));return add(state,linear(hidden,w.feedforward_out,d));}
std::pair<Tensor,Tensor> masked_descriptors(const Tensor&text,const BooleanMask&a,const BooleanMask&b){const auto s=text.shape();auto one=[&](const BooleanMask&m){if(m.shape().size()!=2||m.shape()[0]!=s[0]||m.shape()[1]!=s[1])throw std::invalid_argument("descriptor masks must match the text World sequence");std::vector<double>v(s[0]*s[2]);for(std::size_t row=0;row<s[0];++row){std::size_t n=0;for(std::size_t t=0;t<s[1];++t)if(m.at(row,t)){++n;for(std::size_t d=0;d<s[2];++d)v[row*s[2]+d]+=text.values()[(row*s[1]+t)*s[2]+d];}if(!n)throw std::invalid_argument("every descriptor mask must select text");for(std::size_t d=0;d<s[2];++d)v[row*s[2]+d]/=n;}return Tensor(text.dtype(),{s[0],s[2]},std::move(v),std::string(text.device()));};return{one(a),one(b)};}

} // namespace

void MosaicOmniWorldPipelineConfig::validate() const{world.validate();if(!attention_heads||world.world_dim%attention_heads||!world_ffn_dim||!world_rounds||object_slots!=world.object_slots||!(video_temporal_delta_scale>0))throw std::invalid_argument("invalid World pipeline configuration");}
MosaicOmniWorldPipeline::MosaicOmniWorldPipeline(MosaicOmniWorldPipelineConfig c,MosaicOmniWorldPipelineWeights w,MosaicOmniWorldPipelineModules m):config_(std::move(c)),weights_(std::move(w)),modules_(m){config_.validate();if(!modules_.to_world)throw std::invalid_argument("ModalToWorldAdapter is required");const auto d=config_.world.world_dim;linear_shape(weights_.world_cell.feedforward_in,d,config_.world_ffn_dim);linear_shape(weights_.world_cell.feedforward_out,config_.world_ffn_dim,d);if(weights_.video_object_to_world)linear_shape(*weights_.video_object_to_world,weights_.video_object_to_world->weight.size()/d,d);if(weights_.video_temporal_to_world)linear_shape(*weights_.video_temporal_to_world,weights_.video_temporal_to_world->weight.size()/d,d);if(weights_.video_temporal_delta_to_world)linear_shape(*weights_.video_temporal_delta_to_world,weights_.video_temporal_delta_to_world->weight.size()/d,d);}

MosaicOmniWorldPipelineOutput MosaicOmniWorldPipeline::forward(const MosaicOmniWorldPipelineInputs&in)const{
    if(in.source_tokens.size()!=in.source_masks.size()||in.source_tokens.size()!=in.modalities.size())throw std::invalid_argument("source token, mask, and modality counts must match");for(std::size_t i=0;i<in.source_tokens.size();++i){const auto ts=in.source_tokens[i].shape(),ms=in.source_masks[i].shape();if(ts.size()!=3||ms.size()!=2||ts[0]!=ms[0]||ts[1]!=ms[1])throw std::invalid_argument("each source mask must match its source tokens");}const auto source=concat_tokens(in.source_tokens);const auto source_mask=concat_masks(in.source_masks);std::string source_name="unified:";for(std::size_t i=0;i<in.modalities.size();++i){if(i)source_name+='+';source_name+=in.modalities[i];}auto initial=modules_.to_world->forward(source,&source_mask,std::move(source_name));const auto s=initial.semantic_slots().shape();const auto batch=static_cast<std::size_t>(s[0]),slots=static_cast<std::size_t>(s[1]),dim=static_cast<std::size_t>(s[2]);std::vector<double>world(initial.semantic_slots().values().begin(),initial.semantic_slots().values().end());
    if(in.camera_pose_states){const auto cs=in.camera_pose_states->shape();if(cs.size()!=3||cs[0]!=batch||!cs[1]||cs[2]!=dim)throw std::invalid_argument("camera pose state shape mismatch");add_row_slots(world,batch,slots,dim,20,*in.camera_pose_states,0);add_row_slots(world,batch,slots,dim,21,*in.camera_pose_states,cs[1]-1);}
    if(in.action_summary){const auto as=in.action_summary->shape();if(as.size()!=2||as[0]!=batch||as[1]!=dim)throw std::invalid_argument("action summary shape mismatch");Tensor expanded(in.action_summary->dtype(),{batch,1,dim},{in.action_summary->values().begin(),in.action_summary->values().end()},std::string(in.action_summary->device()));add_row_slots(world,batch,slots,dim,16,expanded);}
    const bool any_masks=in.subject_descriptor_mask.has_value()||in.object_descriptor_mask.has_value(),any_inputs=in.subject_descriptor_input_ids.has_value()||in.object_descriptor_input_ids.has_value();if(any_masks&&any_inputs)throw std::invalid_argument("descriptor masks and descriptor inputs are exclusive");std::optional<std::pair<Tensor,Tensor>>descriptors;
    if(any_inputs){if(!in.subject_descriptor_input_ids||!in.object_descriptor_input_ids)throw std::invalid_argument("object binding requires both descriptor inputs");if(!in.descriptor_text_core||!in.descriptor_projection)throw std::invalid_argument("descriptor encoder contract is unavailable");descriptors.emplace(encode_text_descriptor(*in.descriptor_text_core,*in.subject_descriptor_input_ids,*in.descriptor_projection),encode_text_descriptor(*in.descriptor_text_core,*in.object_descriptor_input_ids,*in.descriptor_projection));}
    else if(any_masks){if(!in.subject_descriptor_mask||!in.object_descriptor_mask)throw std::invalid_argument("object binding requires both descriptor masks");descriptors=masked_descriptors(in.text_world,*in.subject_descriptor_mask,*in.object_descriptor_mask);}
    std::optional<Tensor>relation_logits,object_attention;
    if(descriptors){if(in.image_patch_tokens&&in.image_patch_grid&&modules_.relation_grounder){if(!modules_.relation_head)throw std::runtime_error("explicit relation head is unavailable");const auto grounded=modules_.relation_grounder->forward(*in.image_patch_tokens,descriptors->first,descriptors->second,in.image_patch_grid->first,in.image_patch_grid->second);object_attention=grounded.attention;const auto gs=grounded.slots.shape();if(gs.size()!=3||gs[0]!=batch||gs[1]!=3||gs[2]!=dim)throw std::runtime_error("explicit grounding slot shape mismatch");Tensor relation(grounded.slots.dtype(),{batch,dim},std::vector<double>(batch*dim),std::string(grounded.slots.device()));auto rv=std::vector<double>(relation.values().begin(),relation.values().end());for(std::size_t b=0;b<batch;++b)std::copy_n(grounded.slots.values().begin()+static_cast<std::ptrdiff_t>((b*3+2)*dim),dim,rv.begin()+static_cast<std::ptrdiff_t>(b*dim));relation=Tensor(grounded.slots.dtype(),{batch,dim},std::move(rv),std::string(grounded.slots.device()));relation_logits=modules_.relation_head->forward(relation);for(std::size_t b=0;b<batch;++b)for(std::size_t k=0;k<3;++k){const auto destination=k<2?k:config_.object_slots;for(std::size_t d=0;d<dim;++d)world[(b*slots+destination)*dim+d]+=grounded.slots.values()[(b*3+k)*dim+d];}}
        else if(!config_.video_pair_trajectory_binding_available&&!config_.video_descriptor_trajectory_binding_available)throw std::invalid_argument("descriptor masks require image grounding or video pair binding");}
    Tensor world_tensor(initial.semantic_slots().dtype(),{batch,slots,dim},world,std::string(initial.semantic_slots().device()));
    if(modules_.visual_teacher_slot_bridge&&in.image_patch_tokens&&in.image_patch_grid)world_tensor=add(world_tensor,modules_.visual_teacher_slot_bridge->forward(world_tensor,*in.image_patch_tokens,in.image_patch_grid->first,in.image_patch_grid->second));world.assign(world_tensor.values().begin(),world_tensor.values().end());
    if(in.video_object_slots){if(!weights_.video_object_to_world)throw std::runtime_error("video object projection is unavailable");const auto projected=linear(*in.video_object_slots,*weights_.video_object_to_world,dim);for(std::size_t slot=0;slot<config_.object_slots;++slot)add_row_slots(world,batch,slots,dim,slot,projected,slot);}
    std::optional<Tensor>video_summary,video_delta_world;if(in.video_temporal_summary){if(!weights_.video_temporal_to_world)throw std::runtime_error("video temporal projection is unavailable");video_summary=linear(*in.video_temporal_summary,*weights_.video_temporal_to_world,dim);Tensor expanded(video_summary->dtype(),{batch,1,dim},{video_summary->values().begin(),video_summary->values().end()},std::string(video_summary->device()));add_row_slots(world,batch,slots,dim,slots-1,expanded);}
    if(in.video_temporal_delta){if(!weights_.video_temporal_to_world)throw std::runtime_error("video temporal projection is unavailable");auto scaled_values=std::vector<double>(in.video_temporal_delta->values().begin(),in.video_temporal_delta->values().end());for(auto&v:scaled_values)v*=config_.video_temporal_delta_scale;Tensor scaled(in.video_temporal_delta->dtype(),{in.video_temporal_delta->shape().begin(),in.video_temporal_delta->shape().end()},std::move(scaled_values),std::string(in.video_temporal_delta->device()));if(weights_.video_temporal_delta_to_world)video_delta_world=linear(scaled,*weights_.video_temporal_delta_to_world,dim);else{auto no_bias=*weights_.video_temporal_to_world;no_bias.bias.clear();video_delta_world=linear(scaled,no_bias,dim,false);}Tensor expanded(video_delta_world->dtype(),{batch,1,dim},{video_delta_world->values().begin(),video_delta_world->values().end()},std::string(video_delta_world->device()));add_row_slots(world,batch,slots,dim,16,expanded);}
    if(in.audio_world_summary){Tensor expanded(in.audio_world_summary->dtype(),{batch,1,dim},{in.audio_world_summary->values().begin(),in.audio_world_summary->values().end()},std::string(in.audio_world_summary->device()));add_row_slots(world,batch,slots,dim,slots-1,expanded);}
    std::optional<Tensor>audio_events,audio_content;if(in.audio_temporal_features&&(weights_.audio_event_slot_projection||config_.audio_temporal_head_available))audio_events=adaptive_two(*in.audio_temporal_features);if(in.audio_content_features)audio_content=adaptive_two(*in.audio_content_features);
    std::optional<Tensor>projected_events,projected_content;if(audio_events&&weights_.audio_event_slot_projection){projected_events=linear(*audio_events,*weights_.audio_event_slot_projection,dim);add_row_slots(world,batch,slots,dim,26,*projected_events,0);add_row_slots(world,batch,slots,dim,27,*projected_events,1);}if(audio_content){if(!weights_.audio_content_to_world)throw std::runtime_error("audio content projection is unavailable");projected_content=linear(*audio_content,*weights_.audio_content_to_world,dim);add_row_slots(world,batch,slots,dim,26,*projected_content,0);add_row_slots(world,batch,slots,dim,27,*projected_content,1);}
    world_tensor=Tensor(initial.semantic_slots().dtype(),{batch,slots,dim},std::move(world),std::string(initial.semantic_slots().device()));for(std::size_t round=0;round<config_.world_rounds;++round)world_tensor=world_cell(world_tensor,initial.active_mask(),config_,weights_.world_cell);world.assign(world_tensor.values().begin(),world_tensor.values().end());
    if(projected_events){add_row_slots(world,batch,slots,dim,26,*projected_events,0,true);add_row_slots(world,batch,slots,dim,27,*projected_events,1,true);}if(projected_content){add_row_slots(world,batch,slots,dim,26,*projected_content,0);add_row_slots(world,batch,slots,dim,27,*projected_content,1);}
    WorldState result(Tensor(initial.semantic_slots().dtype(),{batch,slots,dim},std::move(world),std::string(initial.semantic_slots().device())),initial.active_mask(),initial.dirty_mask(),std::string(initial.source()),{initial.surface_refs().begin(),initial.surface_refs().end()});result.validate(config_.world);return{std::move(result),std::move(descriptors),std::move(relation_logits),std::move(object_attention),std::move(video_summary),std::move(video_delta_world),std::move(audio_events),std::move(audio_content)};
}

} // namespace swegca::world
